# Generated by Django 3.0.2 on 2020-02-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('leave', '0004_auto_20200201_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
