# Generated by Django 3.0.2 on 2020-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20200201_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
