# Generated by Django 3.0.2 on 2020-02-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leave_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
