# Generated by Django 3.0.2 on 2020-01-31 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fliale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Fliale',
                'verbose_name_plural': 'Fliales',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MSS', 'Mss'), ('DR', 'Dr'), ('SIR', 'Sir'), ('MADAM', 'Madam')], default='MR', max_length=10, null=True, verbose_name='Title')),
                ('image', models.FileField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image')),
                ('get_full_name', models.CharField(max_length=125, verbose_name='Fullname')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=8, verbose_name='Gender')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+221771239025', help_text='Enter number with Country Code Eg. +221771239025', max_length=128, region=None, verbose_name='Phone Number (Example +221771239025)')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('place_of_birth', models.CharField(choices=[('Dakar', 'Dakar'), ('Guédiawaye', 'Guédiawaye'), ('Pikine', 'Pikine'), ('Bargny', 'Bargny'), ('Diamniadio', 'Diamniadio'), ('Rufisque', 'Rufisque'), ('Sébikhotane', 'Sébikhotane'), ('Bambey', 'Bambey'), ('Diourbel', 'Diourbel'), ('Mbacké', 'Mbacké'), ('Diofior', 'Diofior'), ('Fatick', 'Fatick'), ('Foundiougne', 'Foundiougne'), ('Karang', 'Karang'), ('Passy', 'Passy'), ('Sokone', 'Sokone'), ('Soum', 'Soum'), ('Gossas', 'Gossas'), ('Birkelane', 'Birkelane'), ('Kaffrine', 'Kaffrine'), ('Nganda', 'Nganda'), ('Koungheul', 'Koungheul'), ('Malem-Hodar', 'Malem-Hodar'), ('Guinguinéo', 'Guinguinéo'), ('Mboss', 'Mboss'), ('Gandiaye', 'Gandiaye'), ('Kahone', 'Kahone'), ('Kaolack', 'Kaolack'), ('Ndoffane', 'Ndoffane'), ('Sibassor', 'Sibassor'), ('Nioro_du_Rip', 'Nioro_du_Rip'), ('keur_Madiabel', 'keur_Madiabel'), ('Kédougou', 'Kédougou'), ('Salemata', 'Salemata'), ('Saraya', 'Saraya'), ('Kolda', 'Kolda'), ('Dabo', 'Dabo'), ('Salikégné', 'Salikégné'), ('Médina_Yoro_Foulah', 'Médina_Yoro_Foulah'), ('Pata', 'Pata'), ('Vélingara', 'Vélingara'), ('Kounkané', 'Kounkané'), ('Diaobé_Kabendou', 'Diaobé_Kabendou'), ('Kébémer', 'Kébémer'), ('Guéoul', 'Guéoul'), ('Dahra', 'Dahra'), ('Linguère', 'Linguère'), ('Louga', 'Louga'), ('Ndiagne', 'Ndiagne'), ('Niomré', 'Niomré'), ('Dembakané', 'Dembakané'), ('Hamady_Hounaré', 'Hamady_Hounaré'), ('Kanel', 'Kanel'), ('Semmé', 'Semmé'), ('Aouré', 'Aouré'), ('Bokiladji', 'Bokiladji'), ('Sinthiou', 'Sinthiou'), ('Bamambé', 'Bamambé'), ('Banadji', 'Banadji'), ('Waounde', 'Waounde'), ('Matam', 'Matam'), ('Ourossogui', 'Ourossogui'), ('Thilogne', 'Thilogne'), ('Agnam_Civol', 'Agnam_Civol'), ('Bokidiawé', 'Bokidiawé'), ('Ranérou', 'Ranérou'), ('Dagana', 'Dagana'), ('Gaé', 'Gaé'), ('Richard_Toll', 'Richard_Toll'), ('Ross_Béthio', 'Ross_Béthio'), ('Rosso', 'Rosso'), ('Aéré_Lao', 'Aéré_Lao'), ('Bodé_Lao', 'Bodé_Lao'), ('Démette', 'Démette'), ('Galoya_Toucouleur', 'Galoya_Toucouleur'), ('Golléré', 'Golléré'), ('Guédé_Chantier', 'Guédé_Chantier'), ('Mboumba', 'Mboumba'), ('Niandane', 'Niandane'), ('Ndioum', 'Ndioum'), ('Pété', 'Pété'), ('Podor', 'Podor'), ('Walaldé', 'Walaldé'), ('Saint_Louis', 'Saint_Louis'), ('Mpal', 'Mpal'), ('Bounkiling', 'Bounkiling'), ('Madina_Wandifa', 'Madina_Wandifa'), ('Diattacounda', 'Diattacounda'), ('Goudomp', 'Goudomp'), ('Samine', 'Samine'), ('Tanaff', 'Tanaff'), ('Diannah_Malary', 'Diannah_Malary'), ('Marsassoum', 'Marsassoum'), ('Sédhiou', 'Sédhiou'), ('Bakel', 'Bakel'), ('Diawara', 'Diawara'), ('Kidira', 'Kidira'), ('Goudiry', 'Goudiry'), ('Kothiary', 'Kothiary'), ('Koumpentoum', 'Koumpentoum'), ('Malem_Niani', 'Malem_Niani'), ('Tambacounda', 'Tambacounda'), ('Joal_Fadiouth', 'Joal_Fadiouth'), ('Mbour', 'Mbour'), ('Ngaparou', 'Ngaparou'), ('Nguékhokh', 'Nguékhokh'), ('Popenguine_Ndayane', 'Popenguine_Ndayane'), ('Saly_Portudal', 'Saly_Portudal'), ('Somone', 'Somone'), ('Thiadiaye', 'Thiadiaye'), ('Ndiaganiao', 'Ndiaganiao'), ('Thiès', 'Thiès'), ('Kayar', 'Kayar'), ('Khombole', 'Khombole'), ('Pout', 'Pout'), ('Mboro', 'Mboro'), ('Meckhe', 'Meckhe'), ('Tivaouane', 'Tivaouane'), ('Bignona', 'Bignona'), ('Thionck_Essyl', 'Thionck_Essyl'), ('Diouloulou', 'Diouloulou'), ('Oussouye', 'Oussouye'), ('Ziguinchor', 'Ziguinchor')], default='Dakar', help_text='what town of the country(senegal) are you from ?', max_length=20, null=True, verbose_name='Region')),
                ('address', models.CharField(blank=True, help_text='address of current residence', max_length=125, null=True, verbose_name='Address')),
                ('startdate', models.DateField(help_text='date of employement', null=True, verbose_name='Employement Date')),
                ('is_blocked', models.BooleanField(default=False, help_text='button to toggle employee block and unblock', verbose_name='Is Blocked')),
                ('is_deleted', models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('fliale', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Fliale', verbose_name='Fliales')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Role', verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created'],
            },
        ),
    ]
