# Generated by Django 3.0.2 on 2020-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200203_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='about',
            field=models.TextField(blank=True, help_text='See for example the meeting agenda.', max_length=150, null=True),
        ),
    ]
